### PR TITLE
Fix for RemoteDurationSpec and RemoteInstantSpec

### LINKED ISSUE #51: Unit test failures in Remote[Instant] and Remote[Duration]

### PR DESCRIPTION
**Pull request by igrebenik**
Hey guys!
This is an attempt to close #51 
There were few minor problems that fail mentioned specs:
 -  each time you get a new instance of `Remote[Duration]` (or `Remote[Instant]`) by adding/subtracting time units, the nano-adjustment has not been taken into account;
 - The tests also fail wherever the value of `Gen.anyLong` is added to/subtracted from an instance of Duration (or Instant) and the resulting value falls outside the boundaries of [Duration.Min...Duration.Max] (same for Instant)

### CODE REVIEW

File: zio-flow/shared/src/main/scala/zio/flow/remote/RemoteDurationSyntax.scala [hunk 1]
```diff
@@ -24,16 +24,19 @@ import java.time.temporal.{Temporal, TemporalAmount}
 class RemoteDurationSyntax(val self: Remote[Duration]) extends AnyVal {
 
   def plusDuration2(that: Remote[Duration]): Remote[Duration] =
```
Comment (ashprakasan) [inline zio-flow/shared/src/main/scala/zio/flow/remote/RemoteDurationSyntax.scala:26]: > 
```suggestion
  def plusDuration(that: Remote[Duration]): Remote[Duration] =
```

Comment (igrebenik) [reply zio-flow/shared/src/main/scala/zio/flow/remote/RemoteDurationSyntax.scala]: Yes! Will do)

**Comment by ashprakasan** [comment]
Thanks for the contribution, @igrebenik 
IMO it is better to directly use the native Java `Duration` and `Instant` functions, than creating a (seconds, nanos).

So, we could have case classes for - 

1. DurationPlusDuration (implemented using [`public Duration plus(Duration duration)`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#plus-java.time.Duration-))  
2. DurationMinusDuration ([`public Duration minus(Duration duration)`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#minus-java.time.Duration-))
3. InstantPlusDuration ([`public Instant plus(TemporalAmount amountToAdd)`](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#plus-java.time.temporal.TemporalAmount-))
4. InstantMinusDuration ([`public Instant minus(TemporalAmount amountToSubtract)`](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#minus-java.time.temporal.TemporalAmount-))
5. DurationFromTemporalAmount

I think these should be sufficient to implement other functions  like `plusMillis`, `plusNanos`, `plusSeconds` etc.

**Review by ashprakasan — DISMISSED** [review]
